### ISSUE TITLE
Publish, Client, Documentation - model-card [6.5pt]

### ISSUE THREAD

**Issue by nilssonemma** [payfunc/model-card#134]
- [ ] Rename and publish [0.5pt]
- [x] Create a Client [2pt]
- [x] Make postman scripts [3pt]
- [x] Documentation [1pt]
